import React, { useEffect, useMemo, useState } from 'react';
import { Copy, RotateCcw, Save } from 'lucide-react';
import { projectService } from '../../projects/project-service';
import { compareScoreSummaries, renameRevision, restoreRevision, summarizeScore } from '../../projects/revision-utils';
import type { MusicProjectBundle } from '../../projects/types';

interface Props { bundle?: MusicProjectBundle; onChange?: (bundle: MusicProjectBundle) => void; readOnly?: boolean; }
const reasonLabel:Record<string,string>={compose:'Sáng tác',arrange:'Phối khí',edit:'Chỉnh sửa','section-ai':'AI theo đoạn',restore:'Khôi phục',duplicate:'Bản sao'};
export const RevisionsPanel:React.FC<Props>=({bundle,onChange,readOnly})=>{
 const [renaming,setRenaming]=useState<string|null>(null); const [label,setLabel]=useState(''); const [message,setMessage]=useState<string|null>(null);
 const revisions=useMemo(()=>bundle?[...bundle.revisions].sort((a,b)=>b.createdAt-a.createdAt):[],[bundle]);
 const [compareA,setCompareA]=useState(''); const [compareB,setCompareB]=useState('');
 useEffect(()=>{if(!bundle)return;const ids=new Set(bundle.revisions.map(item=>item.id));const active=bundle.project.activeRevisionId;const other=revisions.find(item=>item.id!==active)?.id||active;if(!ids.has(compareA))setCompareA(active);if(!ids.has(compareB)||compareB===active&&other!==active)setCompareB(other);},[bundle?.project.id,bundle?.project.activeRevisionId,bundle?.revisions.length]);
 const comparison=useMemo(()=>{if(!bundle||!compareA||!compareB)return null;const a=bundle.revisions.find(item=>item.id===compareA);const b=bundle.revisions.find(item=>item.id===compareB);if(!a||!b)return null;return {a,b,aSummary:summarizeScore(a.musicXml),bSummary:summarizeScore(b.musicXml),fields:compareScoreSummaries(summarizeScore(a.musicXml),summarizeScore(b.musicXml))};},[bundle,compareA,compareB]);
 if(!bundle)return <div className="rounded-xl border border-white/10 p-5 text-sm text-zinc-500">Dự án chưa được lưu nên chưa có lịch sử phiên bản.</div>;
 const persist=async(next:MusicProjectBundle)=>{await projectService.saveProject(next);onChange?.(next);};
 const doRestore=async(id:string)=>{if(readOnly)return;const next=restoreRevision(bundle,id,Date.now(),`revision-${crypto.randomUUID?.()||Date.now()}`);await persist(next);setMessage('Đã khôi phục thành một phiên bản mới; lịch sử cũ được giữ nguyên.');};
 const doRename=async(id:string)=>{if(readOnly)return;const next=renameRevision(bundle,id,label);await persist(next);setRenaming(null);setMessage('Đã đổi tên phiên bản.');};
 const duplicate=async(id:string)=>{if(readOnly)return;const duplicated=await projectService.duplicateFromRevision(bundle,id);setMessage(`Đã tạo dự án bản sao: ${duplicated.project.title}`);};
 return <div id="workspace-panel-versions" role="tabpanel" className="space-y-3">
  {message&&<div className="rounded-lg bg-emerald-500/10 px-3 py-2 text-xs text-emerald-300">{message}</div>}
  {bundle.revisions.length>1&&<div className="rounded-xl border border-white/10 bg-white/[0.03] p-4"><div className="mb-3 text-sm font-bold">So sánh phiên bản</div><div className="grid gap-2 sm:grid-cols-2"><select aria-label="Phiên bản A" value={compareA} onChange={e=>setCompareA(e.target.value)} className="rounded-lg border border-white/10 bg-black px-3 py-2 text-xs text-white">{revisions.map(rev=><option key={rev.id} value={rev.id}>A · {rev.label}</option>)}</select><select aria-label="Phiên bản B" value={compareB} onChange={e=>setCompareB(e.target.value)} className="rounded-lg border border-white/10 bg-black px-3 py-2 text-xs text-white">{revisions.map(rev=><option key={rev.id} value={rev.id}>B · {rev.label}</option>)}</select></div>{comparison&&<div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{([['Tông',comparison.fields.key],['BPM',comparison.fields.bpm],['Thời lượng',comparison.fields.durationSeconds],['Số bè',comparison.fields.partCount],['Số nốt',comparison.fields.noteCount]] as const).map(([name,field])=><div key={name} className={`rounded-lg border px-3 py-2 text-xs ${field.changed?'border-amber-500/30 bg-amber-500/5':'border-white/5 bg-black/20'}`}><div className="text-[10px] uppercase tracking-wider text-zinc-500">{name}</div><div className="mt-1 text-zinc-200">{String(field.before??'—')} → {String(field.after??'—')}</div>{field.changed&&<div className="mt-1 text-[10px] text-amber-300">Đã thay đổi</div>}</div>)}</div>}</div>}
  {revisions.map(rev=>{const summary=summarizeScore(rev.musicXml);const active=bundle.project.activeRevisionId===rev.id;return <div key={rev.id} className={`rounded-xl border p-4 ${active?'border-indigo-500/40 bg-indigo-500/5':'border-white/10 bg-black/20'}`}>
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><span className="font-bold">{rev.label}</span>{active&&<span className="rounded bg-indigo-500/20 px-2 py-0.5 text-[10px] font-bold text-indigo-300">ĐANG DÙNG</span>}</div><div className="mt-1 text-[11px] text-zinc-500">{reasonLabel[rev.reason]||rev.reason} · {new Date(rev.createdAt).toLocaleString()} · {summary.partCount} bè · {summary.noteCount} nốt · {summary.key?`${summary.key} · `:''}{summary.bpm?`${Math.round(summary.bpm)} BPM · `:''}{summary.durationSeconds?`${Math.round(summary.durationSeconds)}s`:''}</div></div>
    <div className="flex flex-wrap gap-2"><button disabled={readOnly} onClick={()=>{setRenaming(rev.id);setLabel(rev.label);}} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Đổi tên</button><button disabled={readOnly} onClick={()=>void doRestore(rev.id)} className="inline-flex items-center gap-1 rounded-lg border border-white/10 px-3 py-2 text-xs"><RotateCcw className="h-3.5 w-3.5"/>Khôi phục</button><button disabled={readOnly} onClick={()=>void duplicate(rev.id)} className="inline-flex items-center gap-1 rounded-lg border border-white/10 px-3 py-2 text-xs"><Copy className="h-3.5 w-3.5"/>Tạo bản sao</button></div></div>
    {renaming===rev.id&&<div className="mt-3 flex gap-2"><input value={label} onChange={e=>setLabel(e.target.value)} className="flex-1 rounded-lg border border-white/10 bg-black px-3 py-2 text-sm"/><button onClick={()=>void doRename(rev.id)} className="inline-flex items-center gap-1 rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold"><Save className="h-3.5 w-3.5"/>Lưu</button></div>}
  </div>;})}
 </div>;
};
