import React, { useMemo, useState } from 'react';
import { Loader2, Sparkles } from 'lucide-react';
import type { MeasureRange } from '../../music/measure-range';
import { summarizeMeasureRange, validateMeasureRange } from '../../music/measure-range';
import { productErrorText } from '../../utils/product-errors';
interface Props { xmlContent:string; styleId:string; onApply:(xml:string,label:string)=>void; readOnly?:boolean; }
export const SectionRevisionPanel:React.FC<Props>=({xmlContent,styleId,onApply,readOnly})=>{
 const [range,setRange]=useState<MeasureRange>({startMeasure:1,endMeasure:1});const [instruction,setInstruction]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState<string|null>(null);
 const rangeSummary=useMemo(()=>{try{return summarizeMeasureRange(xmlContent,range);}catch{return null;}},[range,xmlContent]);
 const revise=async()=>{if(readOnly)return;setError(null);try{validateMeasureRange(xmlContent,range);if(!instruction.trim())throw new Error('Hãy nhập yêu cầu chỉnh sửa.');setLoading(true);const response=await fetch('/api/compose/revise-section',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({musicXml:xmlContent,startMeasure:range.startMeasure,endMeasure:range.endMeasure,instruction,styleId})});const data=await response.json();if(!response.ok){const err:any=new Error(data.error?.message||'Không thể chỉnh đoạn');err.code=data.error?.code;throw err;}if(typeof data.xml!=='string')throw new Error('Máy chủ không trả MusicXML hợp lệ.');onApply(data.xml,`AI chỉnh ô ${range.startMeasure}-${range.endMeasure}`);setInstruction('');}catch(e){setError(productErrorText(e,(e as any)?.message));}finally{setLoading(false);}};
 return <div id="workspace-panel-section" role="tabpanel" className="space-y-4"><div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-4"><div className="font-bold">Chỉnh sửa có kiểm soát theo đoạn</div><p className="mt-1 text-xs text-zinc-400">Chỉ các ô nhịp được chọn mới được AI thay thế. Bản gốc luôn được giữ trong lịch sử phiên bản.</p>{rangeSummary&&<div className="mt-3 flex flex-wrap gap-2 text-[11px] text-amber-100/80"><span className="rounded bg-black/20 px-2 py-1">{rangeSummary.measureCount} ô nhịp</span><span className="rounded bg-black/20 px-2 py-1">{rangeSummary.partIds.length} bè</span><span className="rounded bg-black/20 px-2 py-1">Bè: {rangeSummary.partIds.join(', ')}</span></div>}</div><div className="grid gap-3 md:grid-cols-[120px_120px_1fr]"><label className="text-xs text-zinc-400">Từ ô<input type="number" value={range.startMeasure} onChange={e=>setRange(r=>({...r,startMeasure:Number(e.target.value)}))} className="mt-1 w-full rounded-lg border border-white/10 bg-black px-3 py-2"/></label><label className="text-xs text-zinc-400">Đến ô<input type="number" value={range.endMeasure} onChange={e=>setRange(r=>({...r,endMeasure:Number(e.target.value)}))} className="mt-1 w-full rounded-lg border border-white/10 bg-black px-3 py-2"/></label><label className="text-xs text-zinc-400">Yêu cầu<textarea value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="VD: Làm phần strings nhẹ hơn, giữ nguyên giai điệu chính…" className="mt-1 min-h-24 w-full rounded-lg border border-white/10 bg-black p-3 text-sm"/></label></div><button disabled={readOnly||loading||!instruction.trim()} onClick={()=>void revise()} className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-bold disabled:opacity-40">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<Sparkles className="h-4 w-4"/>} Chỉnh đoạn bằng AI</button>{error&&<div className="text-xs text-red-300">{error}</div>}</div>;
};
