import type { MixState } from '../projects/types';
import type { ScoreTimeline } from '../music/score-timeline';
import { quarterToSeconds } from '../music/score-timeline';
import { renderWithAudioFallback, type AudioRenderQuality } from './render-policy';
import { renderTimelineWithSoundFont } from './soundfont-render';
import { resolveAudibleParts, sanitizeMix } from './mix-state';
import { applyMasterMix } from './mix-render';
import { scheduleSynthNote } from './synth';
export interface WavRenderOptions { sampleRate?:number; channels?:1|2; tailSeconds?:number; quality?:AudioRenderQuality; soundFontUrl?:string; mix?:MixState; }
export async function renderTimelineToBasicWavBlob(timeline:ScoreTimeline,options:WavRenderOptions={}):Promise<Blob>{
 const sampleRate=Math.max(22050,Math.min(44100,Math.round(options.sampleRate||32000))); const cleanMix=options.mix?sanitizeMix(options.mix,timeline):undefined; const channels:1|2=cleanMix?2:(options.channels||1); const tailSeconds=Math.max(.1,Math.min(2,options.tailSeconds||.35)); const duration=Math.max(.25,timeline.totalDurationSeconds+tailSeconds); if(duration>600)throw new Error('Bản nhạc quá dài để kết xuất WAV trên trình duyệt.');
 const OfflineCtor=window.OfflineAudioContext||(window as any).webkitOfflineAudioContext;if(!OfflineCtor)throw new Error('Trình duyệt này không hỗ trợ kết xuất WAV offline.'); const context:OfflineAudioContext=new OfflineCtor(channels,Math.ceil(duration*sampleRate),sampleRate); const master=context.createGain();master.gain.value=cleanMix?1:.82;master.connect(context.destination);
 const audible=cleanMix?resolveAudibleParts(cleanMix):new Set(timeline.parts.map(p=>p.partId));const partScale=1/Math.max(1,Math.sqrt(audible.size));
 for(const part of timeline.parts){if(!audible.has(part.partId))continue;let destination:AudioNode=master;let partGain:GainNode|undefined;let panner:StereoPannerNode|undefined;if(cleanMix){const state=cleanMix.parts[part.partId];partGain=context.createGain();partGain.gain.value=state.volume*partScale;if(channels===2&&typeof context.createStereoPanner==='function'){panner=context.createStereoPanner();panner.pan.value=state.pan;partGain.connect(panner);panner.connect(master);}else partGain.connect(master);destination=partGain;} for(const note of part.events){const start=quarterToSeconds(note.startQuarter,timeline.tempoMap);const end=quarterToSeconds(note.startQuarter+note.durationQuarter,timeline.tempoMap);scheduleSynthNote(context,destination,note,{...part,midiProgram:cleanMix?.parts[part.partId]?.midiProgram??part.midiProgram},start,Math.max(.03,end-start),cleanMix?1:partScale);}}
 const audioBuffer=await context.startRendering(); if(cleanMix&&audioBuffer.numberOfChannels>=2)applyMasterMix(audioBuffer.getChannelData(0),audioBuffer.getChannelData(1),sampleRate,cleanMix); return audioBufferToWavBlob(audioBuffer);
}
export interface WavRenderResult { blob: Blob; renderer: 'soundfont' | 'basic'; fallbackError?: unknown; }
export async function renderTimelineToWavResult(timeline:ScoreTimeline,options:WavRenderOptions={}):Promise<WavRenderResult>{const quality=options.quality||'auto';const result=await renderWithAudioFallback(quality,()=>renderTimelineWithSoundFont(timeline,{sampleRate:options.sampleRate,tailSeconds:options.tailSeconds,soundFontUrl:options.soundFontUrl,mix:options.mix}),()=>renderTimelineToBasicWavBlob(timeline,options));if(result.renderer==='basic'&&result.fallbackError)console.warn('SoundFont preview unavailable; using basic renderer.',result.fallbackError);return {blob:result.value,renderer:result.renderer,fallbackError:result.fallbackError};}
export async function renderTimelineToWavBlob(timeline:ScoreTimeline,options:WavRenderOptions={}):Promise<Blob>{return (await renderTimelineToWavResult(timeline,options)).blob;}
export function audioBufferToWavBlob(buffer:AudioBuffer):Blob{const channels=buffer.numberOfChannels,sampleRate=buffer.sampleRate,frames=buffer.length,bytesPerSample=2,blockAlign=channels*bytesPerSample,dataSize=frames*blockAlign,arrayBuffer=new ArrayBuffer(44+dataSize),view=new DataView(arrayBuffer);writeAscii(view,0,'RIFF');view.setUint32(4,36+dataSize,true);writeAscii(view,8,'WAVE');writeAscii(view,12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,channels,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*blockAlign,true);view.setUint16(32,blockAlign,true);view.setUint16(34,16,true);writeAscii(view,36,'data');view.setUint32(40,dataSize,true);const channelData=Array.from({length:channels},(_,i)=>buffer.getChannelData(i));let offset=44;for(let frame=0;frame<frames;frame++)for(let channel=0;channel<channels;channel++){const sample=Math.max(-1,Math.min(1,channelData[channel][frame]||0));const pcm=sample<0?sample*0x8000:sample*0x7fff;view.setInt16(offset,Math.round(pcm),true);offset+=2;}return new Blob([arrayBuffer],{type:'audio/wav'});}
function writeAscii(view:DataView,offset:number,text:string):void{for(let i=0;i<text.length;i++)view.setUint8(offset+i,text.charCodeAt(i));}
